version: "3"

networks:
  stack-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

services:
  gitlab:
    image: ${GITLAB_IMAGE}
    restart: always
    hostname: "${GITLAB_HOSTNAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL}'
        letsencrypt['enabled'] = false
        nginx['enabled'] = false
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${GITLAB_SMTP_SERVER}"
        gitlab_rails['smtp_port'] = ${GITLAB_SMTP_PORT}
        gitlab_rails['smtp_user_name'] = "${GITLAB_SMTP_USER}"
        gitlab_rails['smtp_password'] = "${GITLAB_SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${GITLAB_SMTP_DOMAIN}"
        gitlab_rails['smtp_authentication'] = "${GITLAB_SMTP_AUTHENTICATION}"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = '${GITLAB_EMAIL_FROM}'
        gitlab_rails['gitlab_email_reply_to'] = '${GITLAB_EMAIL_REPLY}'
        gitlab_rails['gitlab_shell_ssh_port'] = 30022
    ports:
      - "30080:80"
      - "30022:22"
    networks:
      - stack-net
    volumes:
      - ${GITLAB_DATA}/config:/etc/gitlab:rw
      - ${GITLAB_DATA}/log:/var/log/gitlab:rw
      - ${GITLAB_DATA}/data:/var/opt/gitlab:rw
